### ISSUE TITLE
GOHA GUI Profile name null

### ISSUE THREAD

**Issue by LucasT-dev** [LucasT-dev/Expert-Build-Plugin#19]
https://www.spigotmc.org/threads/expert-build.605436/page-2#post-4683870

[21:21:42 WARN]: [ExpertBuild] Task #12 for ExpertBuild v1.18.1.13 generated an exception
java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-6.0.52.jar:?]
        at fr.marodeur.expertbuild.object.ItemBuilder.setSkullTextures(ItemBuilder.java:195) ~[ExpertBuild-v1.18.1.x.jar:?]
        at fr.marodeur.expertbuild.gui.OrganicGUI$1.init(OrganicGUI.java:42) ~[ExpertBuild-v1.18.1.x.jar:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.initProvider(RyseInventory.java:1211) ~[?:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.initInventory(RyseInventory.java:646) ~[?:?]
        at io.github.rysefoxx.inventory.plugin.pagination.RyseInventory.lambda$open$8(RyseInventory.java:551) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-381]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-381]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LucasT-dev** [comment]
Delete mojang authlib : Cxeb68d52e-5509 3.7 Exposure of Sensitive Information to an Unauthorized Actor vulnerability with Low severity found
