### ISSUE TITLE
1.20.4 shutdown error

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [LucasT-dev/Expert-Build-Plugin#26]
Hello, we just have updated to 1.20.4 and ever since get the following error once someone quits:
`[16:08:12 ERROR]: Could not pass event PlayerQuitEvent to ExpertBuild v1.18.1.17
java.lang.NullPointerException: Cannot invoke "fr.marodeur.expertbuild.object.GOHA_Builder.setPregen(boolean)" because "goha_builder" is null
        at fr.marodeur.expertbuild.listeners.GeneralListener.onQuit(GeneralListener.java:94) ~[ExpertBuild-v1.18.1.17.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:613) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:598) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2093) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2073) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2060) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:838) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1746) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by LucasT-dev** [comment]
fixed in the next update
